[project]
name = "ingest"
version = "1.0.0"
description = "Add your description here"
requires-python = ">=3.13"
authors = [
    { name = "Haruna Musoke", email = "musokeharuna90@gmail.com" },
]
readme = "README.md"

[project.scripts]
ingest = "ingest.__main__:main"

[project.urls]
repository = "https://github.com/yotv-aardvark/outpost-trench.git"
issues = "https://github.com/yotv-aardvark/outpost-trench/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.report]
fail_under = 100
omit = ["__main__.py"]

[tool.coverage.run]
source = ["ingest"]

[tool.hatch.build.targets.sdist]
include = ["src"]

dependencies = [
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
